spring:
  application:
    name: BekooCinema
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            hosts: ${elastic.host}
            username: ${elastic.username}
            password: ${elastic.password}
            analysis:
              configurer: org.beautybox.config.ElasticsearchAnalysisConfig
          schema_management:
            strategy: create-or-update
    hibernate:
      ddl-auto: update
  mail:
    username: ${mail.user}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  web:
    resources:
      add-mappings: false